//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public int ID { get; set; }
        public string DistrictName { get; set; }
        public string DistrictCode { get; set; }
        public string StateName { get; set; }
    }
}
