//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTEmail
    {
        public int EmaidID { get; set; }
        public string Email { get; set; }
        public int UserID { get; set; }
        public string Password { get; set; }
    }
}
