//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTOrderStatu
    {
        public int Id { get; set; }
        public string StatusName { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<System.DateTime> UIDDate { get; set; }
        public Nullable<int> EID { get; set; }
        public Nullable<System.DateTime> EIDDate { get; set; }
    }
}
