//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersView
    {
        public int OrderId { get; set; }
        public string OrderNo { get; set; }
        public string WayBillNo { get; set; }
        public string CourierName { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public string AgentName { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeNumber { get; set; }
        public string AddressLine1 { get; set; }
        public string AlternatePhoneNo { get; set; }
        public string Post { get; set; }
        public string Taluk { get; set; }
        public string District { get; set; }
        public string Pincode { get; set; }
        public string MobileNo { get; set; }
        public string Product { get; set; }
        public string Amount { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<System.DateTime> UIDDate { get; set; }
        public Nullable<int> EID { get; set; }
        public Nullable<System.DateTime> EIDDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmailAddress { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
